package com.restaurant.kitchen.entity;

import com.restaurant.kitchen.enums.ChefStatus;
import com.restaurant.kitchen.enums.Station;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class ChefProfile {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "chef_seq")
    @SequenceGenerator(
            name = "chef_seq",
            sequenceName = "chef_id_seq",
            allocationSize = 1 // allocationSize set to 1 because chef numbers are usually small
    )
    private Long id; // PK, auto-generated by PostgresSQL sequence

    @Column(name = "auth_user_id", nullable = false , unique = true)
    private Long authUserId ;

    @Column(name = "display_name" , nullable = false)
    private String displayName;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private Station station = Station.UNASSIGNED;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private ChefStatus status = ChefStatus.ACTIVE;

    //Lazy to prevent loading all tickets unless explicitly accessed
    @OneToMany(mappedBy = "assignedChef" , fetch = FetchType.LAZY)
    @Builder.Default
    private List <KitchenTicket> assignedTickets = new ArrayList<>() ;
}
