package com.restaurant.kitchen.entity;

import com.restaurant.kitchen.enums.TicketStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class KitchenTicket {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ticket_seq")
    @SequenceGenerator(
            name = "ticket_seq",
            sequenceName = "ticket_id_seq",
            allocationSize = 50 // batch insert optimization , minimize load on DB
    )
    private Long id; // PK, auto-generated by PostgresSQL sequence

    @Column(name = "order_id", nullable = false, unique = true)
    private Long orderId ;

    @Column(nullable = false)
    private TicketStatus status ;

    //Eager due to the close connection between the ticket and the chef
    // one chef can be assigned to many tickets
    // one ticket should be assigned to only one chef
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "assigned_chef_id")
    private ChefProfile assignedChef;


    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt ;
}
