package com.restaurant.client.domain.entity;

import com.restaurant.client.domain.enums.Gender;
import com.restaurant.client.domain.enums.Goal;
import com.restaurant.client.domain.enums.HealthCondition;
import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "client_profiles")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ClientProfile {

    /**
     * We don't use @GeneratedValue here because we want this ID to exactly match
     * the userId generated by the auth-service to maintain a 1:1 relationship.
     */
    @Id
    private Long id;

    private Integer age;

    @Enumerated(EnumType.STRING)
    private Gender gender;

    private Boolean exercisesRegularly;

    private Double height;

    @Column(name = "height_unit")
    private String heightUnit; // e.g., "METER", "FEET"

    private Double weight;

    @Column(name = "weight_unit")
    private String weightUnit; // e.g., "KG", "POUND"

    @Enumerated(EnumType.STRING)
    private Goal goal;

    @Builder.Default
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
            name = "client_health_conditions",
            joinColumns = @JoinColumn(name = "client_id")
    )
    @Enumerated(EnumType.STRING)
    @Column(name = "condition")
    private Set<HealthCondition> healthConditions = new HashSet<>();

    @Column(name = "phone_number")
    private String phoneNumber;

    @Column(name = "profile_picture_url")
    private String profilePictureUrl;

    @Builder.Default
    @Column(name = "loyalty_points")
    private Integer loyaltyPoints = 0;

}
