spring:
  application:
    name: inventory-service

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8080

app:
  rabbitmq:
    exchange: restaurant.events.exchange
    queues:
      menu-nutrition:
        name: menu.nutrition.processed.queue
        routing-key: menu.nutrition.processed
        dlq-name: menu.nutrition.processed.queue.dlq
        dlq-routing-key: menu.nutrition.processed.dlq
